AWSTemplateFormatVersion: 2010-09-09
Description: "EKS cluster for Maintenance Manager"

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: maintenance-manager-vpc

  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: maintenance-manager-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref myInternetGateway

  PublicSubnet1A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "eu-west-1a"
      MapPublicIpOnLaunch: true  #// not needed since we will be accessing the program from the cluster ip addreess - save cost
      Tags:
        - Key: Name
          Value: public-subnet-1a

  PublicSubnet1B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "eu-west-1b"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public-subnet-1b

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: Maintenance-manager-rt

  RouteToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable # add this route into this route table
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref myInternetGateway

  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1A
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1B
      RouteTableId: !Ref RouteTable

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - Key: Name
          Value: eks-cluster-role

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: maintenance-manager-cluster
      Version: "1.34"
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref PublicSubnet1A
          - !Ref PublicSubnet1B
        EndpointPrivateAccess: true  
        EndpointPublicAccess: true  
      AccessConfig:
        AuthenticationMode: API_AND_CONFIG_MAP

  EKSNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy #allows nodes to join cluster
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy #networking
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly #allows pulling the images from ECR
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Tags:
        - Key: Name
          Value: eks-NodeGroup-role
        


  EKSNodegroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      ClusterName: !Ref EKSCluster
      NodeRole: !GetAtt EKSNodeGroupRole.Arn
      Subnets:
        - !Ref PublicSubnet1A
        - !Ref PublicSubnet1B
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 1
      InstanceTypes:
        - t3.medium
      Tags:
        Name: eks-node-group
        